package edu.pitt.isd.model.mapper;

import edu.pitt.isd.controller.question.vo.AnswerVO;
import edu.pitt.isd.model.dto.Answer;
import edu.pitt.isd.model.dto.AnswerExample;
import edu.pitt.isd.model.dto.Evaluation;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface AnswerMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table answer
     *
     * @mbg.generated
     */
    @SelectProvider(type = AnswerSqlProvider.class, method = "countByExample")
    long countByExample(AnswerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table answer
     *
     * @mbg.generated
     */
    @DeleteProvider(type = AnswerSqlProvider.class, method = "deleteByExample")
    int deleteByExample(AnswerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table answer
     *
     * @mbg.generated
     */
    @Delete({ "delete from answer", "where id = #{id,jdbcType=INTEGER}" })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table answer
     *
     * @mbg.generated
     */
    @Insert({ "insert into answer (evaluation_id, question_id, ", "option_number, count)",
            "values (#{evaluationId,jdbcType=INTEGER}, #{questionId,jdbcType=INTEGER}, ",
            "#{optionNumber,jdbcType=INTEGER}, #{count,jdbcType=INTEGER})" })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
    int insert(Answer record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table answer
     *
     * @mbg.generated
     */
    @InsertProvider(type = AnswerSqlProvider.class, method = "insertSelective")
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
    int insertSelective(Answer record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table answer
     *
     * @mbg.generated
     */
    @SelectProvider(type = AnswerSqlProvider.class, method = "selectByExample")
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "evaluation_id", property = "evaluationId", jdbcType = JdbcType.INTEGER),
            @Result(column = "question_id", property = "questionId", jdbcType = JdbcType.INTEGER),
            @Result(column = "option_number", property = "optionNumber", jdbcType = JdbcType.INTEGER),
            @Result(column = "count", property = "count", jdbcType = JdbcType.INTEGER) })
    List<Answer> selectByExampleWithRowbounds(AnswerExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table answer
     *
     * @mbg.generated
     */
    @SelectProvider(type = AnswerSqlProvider.class, method = "selectByExample")
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "evaluation_id", property = "evaluationId", jdbcType = JdbcType.INTEGER),
            @Result(column = "question_id", property = "questionId", jdbcType = JdbcType.INTEGER),
            @Result(column = "option_number", property = "optionNumber", jdbcType = JdbcType.INTEGER),
            @Result(column = "count", property = "count", jdbcType = JdbcType.INTEGER) })
    List<Answer> selectByExample(AnswerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table answer
     *
     * @mbg.generated
     */
    @Select({ "select", "id, evaluation_id, question_id, option_number, count", "from answer",
            "where id = #{id,jdbcType=INTEGER}" })
    @Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "evaluation_id", property = "evaluationId", jdbcType = JdbcType.INTEGER),
            @Result(column = "question_id", property = "questionId", jdbcType = JdbcType.INTEGER),
            @Result(column = "option_number", property = "optionNumber", jdbcType = JdbcType.INTEGER),
            @Result(column = "count", property = "count", jdbcType = JdbcType.INTEGER) })
    Answer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table answer
     *
     * @mbg.generated
     */
    @UpdateProvider(type = AnswerSqlProvider.class, method = "updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Answer record, @Param("example") AnswerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table answer
     *
     * @mbg.generated
     */
    @UpdateProvider(type = AnswerSqlProvider.class, method = "updateByExample")
    int updateByExample(@Param("record") Answer record, @Param("example") AnswerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table answer
     *
     * @mbg.generated
     */
    @UpdateProvider(type = AnswerSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Answer record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table answer
     *
     * @mbg.generated
     */
    @Update({ "update answer", "set evaluation_id = #{evaluationId,jdbcType=INTEGER},",
            "question_id = #{questionId,jdbcType=INTEGER},", "option_number = #{optionNumber,jdbcType=INTEGER},",
            "count = #{count,jdbcType=INTEGER}", "where id = #{id,jdbcType=INTEGER}" })
    int updateByPrimaryKey(Answer record);

    @Insert({ "<script>", "insert into answer (evaluation_id, question_id, option_number, count)",
            "values" + "<foreach item='answer' collection='answers.answers' open='' separator=',' close=''>" + "("
                    + "#{evaluation.id,jdbcType=INTEGER}, #{answer.questionId,jdbcType=INTEGER}, ",
            "#{answer.optionNumber,jdbcType=INTEGER}, 1) " + "</foreach>", "ON DUPLICATE KEY UPDATE count = count + 1",
            "</script>" })
    // @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
    int insertOrUpdate(@Param("answers") AnswerVO answerVo, @Param("evaluation") Evaluation evaluation);
}