package edu.pitt.isd.model.mapper;

import edu.pitt.isd.model.dto.Authorities;
import edu.pitt.isd.model.dto.AuthoritiesExample;
import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface AuthoritiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbg.generated
     */
    @SelectProvider(type=AuthoritiesSqlProvider.class, method="countByExample")
    long countByExample(AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbg.generated
     */
    @DeleteProvider(type=AuthoritiesSqlProvider.class, method="deleteByExample")
    int deleteByExample(AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbg.generated
     */
    @Insert({
        "insert into authorities (username, authority)",
        "values (#{username,jdbcType=VARCHAR}, #{authority,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Authorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbg.generated
     */
    @InsertProvider(type=AuthoritiesSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(Authorities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbg.generated
     */
    @SelectProvider(type=AuthoritiesSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="authority", property="authority", jdbcType=JdbcType.VARCHAR)
    })
    List<Authorities> selectByExampleWithRowbounds(AuthoritiesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbg.generated
     */
    @SelectProvider(type=AuthoritiesSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER),
        @Result(column="username", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="authority", property="authority", jdbcType=JdbcType.VARCHAR)
    })
    List<Authorities> selectByExample(AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AuthoritiesSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Authorities record, @Param("example") AuthoritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authorities
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AuthoritiesSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Authorities record, @Param("example") AuthoritiesExample example);
}