package edu.pitt.isd.model.dto;

import java.util.Date;

public class Course {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column course.id
     * @mbg.generated
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column course.subject
     * @mbg.generated
     */
    private String subject;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column course.number
     * @mbg.generated
     */
    private String number;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column course.year
     * @mbg.generated
     */
    private Date year;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column course.semester
     * @mbg.generated
     */
    private String semester;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column course.dept_id
     * @mbg.generated
     */
    private Integer deptId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column course.instructor_id
     * @mbg.generated
     */
    private Integer instructorId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column course.name
     * @mbg.generated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column course.id
     * @return  the value of course.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column course.id
     * @param id  the value for course.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column course.subject
     * @return  the value of course.subject
     * @mbg.generated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column course.subject
     * @param subject  the value for course.subject
     * @mbg.generated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column course.number
     * @return  the value of course.number
     * @mbg.generated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column course.number
     * @param number  the value for course.number
     * @mbg.generated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column course.year
     * @return  the value of course.year
     * @mbg.generated
     */
    public Date getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column course.year
     * @param year  the value for course.year
     * @mbg.generated
     */
    public void setYear(Date year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column course.semester
     * @return  the value of course.semester
     * @mbg.generated
     */
    public String getSemester() {
        return semester;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column course.semester
     * @param semester  the value for course.semester
     * @mbg.generated
     */
    public void setSemester(String semester) {
        this.semester = semester == null ? null : semester.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column course.dept_id
     * @return  the value of course.dept_id
     * @mbg.generated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column course.dept_id
     * @param deptId  the value for course.dept_id
     * @mbg.generated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column course.instructor_id
     * @return  the value of course.instructor_id
     * @mbg.generated
     */
    public Integer getInstructorId() {
        return instructorId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column course.instructor_id
     * @param instructorId  the value for course.instructor_id
     * @mbg.generated
     */
    public void setInstructorId(Integer instructorId) {
        this.instructorId = instructorId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column course.name
     * @return  the value of course.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column course.name
     * @param name  the value for course.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table course
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Course other = (Course) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getSubject() == null ? other.getSubject() == null : this.getSubject().equals(other.getSubject()))
                && (this.getNumber() == null ? other.getNumber() == null : this.getNumber().equals(other.getNumber()))
                && (this.getYear() == null ? other.getYear() == null : this.getYear().equals(other.getYear()))
                && (this.getSemester() == null ? other.getSemester() == null : this.getSemester().equals(other.getSemester()))
                && (this.getDeptId() == null ? other.getDeptId() == null : this.getDeptId().equals(other.getDeptId()))
                && (this.getInstructorId() == null ? other.getInstructorId() == null
                        : this.getInstructorId().equals(other.getInstructorId()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table course
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getSubject() == null) ? 0 : getSubject().hashCode());
        result = prime * result + ((getNumber() == null) ? 0 : getNumber().hashCode());
        result = prime * result + ((getYear() == null) ? 0 : getYear().hashCode());
        result = prime * result + ((getSemester() == null) ? 0 : getSemester().hashCode());
        result = prime * result + ((getDeptId() == null) ? 0 : getDeptId().hashCode());
        result = prime * result + ((getInstructorId() == null) ? 0 : getInstructorId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        return result;
    }
}