package edu.pitt.isd.model.dto;

public class QuestionOption {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_option.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_option.question_id
     *
     * @mbg.generated
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_option.option_number
     *
     * @mbg.generated
     */
    private Integer optionNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_option.option
     *
     * @mbg.generated
     */
    private String option;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_option.id
     *
     * @return the value of question_option.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_option.id
     *
     * @param id the value for question_option.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_option.question_id
     *
     * @return the value of question_option.question_id
     *
     * @mbg.generated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_option.question_id
     *
     * @param questionId the value for question_option.question_id
     *
     * @mbg.generated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_option.option_number
     *
     * @return the value of question_option.option_number
     *
     * @mbg.generated
     */
    public Integer getOptionNumber() {
        return optionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_option.option_number
     *
     * @param optionNumber the value for question_option.option_number
     *
     * @mbg.generated
     */
    public void setOptionNumber(Integer optionNumber) {
        this.optionNumber = optionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_option.option
     *
     * @return the value of question_option.option
     *
     * @mbg.generated
     */
    public String getOption() {
        return option;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_option.option
     *
     * @param option the value for question_option.option
     *
     * @mbg.generated
     */
    public void setOption(String option) {
        this.option = option == null ? null : option.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_option
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        QuestionOption other = (QuestionOption) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getQuestionId() == null ? other.getQuestionId() == null : this.getQuestionId().equals(other.getQuestionId()))
            && (this.getOptionNumber() == null ? other.getOptionNumber() == null : this.getOptionNumber().equals(other.getOptionNumber()))
            && (this.getOption() == null ? other.getOption() == null : this.getOption().equals(other.getOption()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_option
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getQuestionId() == null) ? 0 : getQuestionId().hashCode());
        result = prime * result + ((getOptionNumber() == null) ? 0 : getOptionNumber().hashCode());
        result = prime * result + ((getOption() == null) ? 0 : getOption().hashCode());
        return result;
    }
}