package edu.pitt.isd.model.dto;

public class Users {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column users.USER
     * @mbg.generated
     */
    private String user;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column users.CURRENT_CONNECTIONS
     * @mbg.generated
     */
    private Long currentConnections;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column users.TOTAL_CONNECTIONS
     * @mbg.generated
     */
    private Long totalConnections;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column users.USER
     * @return  the value of users.USER
     * @mbg.generated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column users.USER
     * @param user  the value for users.USER
     * @mbg.generated
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column users.CURRENT_CONNECTIONS
     * @return  the value of users.CURRENT_CONNECTIONS
     * @mbg.generated
     */
    public Long getCurrentConnections() {
        return currentConnections;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column users.CURRENT_CONNECTIONS
     * @param currentConnections  the value for users.CURRENT_CONNECTIONS
     * @mbg.generated
     */
    public void setCurrentConnections(Long currentConnections) {
        this.currentConnections = currentConnections;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column users.TOTAL_CONNECTIONS
     * @return  the value of users.TOTAL_CONNECTIONS
     * @mbg.generated
     */
    public Long getTotalConnections() {
        return totalConnections;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column users.TOTAL_CONNECTIONS
     * @param totalConnections  the value for users.TOTAL_CONNECTIONS
     * @mbg.generated
     */
    public void setTotalConnections(Long totalConnections) {
        this.totalConnections = totalConnections;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table users
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Users other = (Users) that;
        return (this.getUser() == null ? other.getUser() == null : this.getUser().equals(other.getUser()))
                && (this.getCurrentConnections() == null ? other.getCurrentConnections() == null
                        : this.getCurrentConnections().equals(other.getCurrentConnections()))
                && (this.getTotalConnections() == null ? other.getTotalConnections() == null
                        : this.getTotalConnections().equals(other.getTotalConnections()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table users
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUser() == null) ? 0 : getUser().hashCode());
        result = prime * result + ((getCurrentConnections() == null) ? 0 : getCurrentConnections().hashCode());
        result = prime * result + ((getTotalConnections() == null) ? 0 : getTotalConnections().hashCode());
        return result;
    }
}